### ISSUE TITLE
Error en la hora del evento

### ISSUE THREAD

**Issue by robertohueso** [beerjs/granada#3]
En el evento del 18 de Noviembre _Brujeria con Node.js_, según [Beerjs](https://github.com/beerjs/granada) es a las **18:30** y según [demiurgosoft](https://demiurgosoft.github.io/brujeria-con-node/) es a las **16:30**.

**Comment by vrivas** [comment]
Gracias. Es la información que me habían pasado por correo desde la OSL. Voy a confirmar la hora correcta.

**Comment by angrykoala** [comment]
16:30 miércoles 18

**Comment by vrivas** [comment]
Graaaacias!!

2015-11-10 15:55 GMT+01:00 Andrés notifications@github.com:

> 16:30 miércoles 18
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beerjs/granada/issues/3#issuecomment-155441300.

## 

_Victor Manuel Rivas Santos_

**Comment by robertohueso** [comment]
Fixed in 7318d30363281a825e49fda60a115ac9277b9b6b

**Comment by JJ** [comment]
Tenía reservada el aula a las 18:30. Recuerda que te comenté que tenía
clase y llevaría a los alumnos. Trato de cambiar la reserva.

2015-11-10 22:14 GMT+01:00 robertohueso notifications@github.com:

> Closed #3 https://github.com/beerjs/granada/issues/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beerjs/granada/issues/3#event-460611804.

## 

JJ

**Comment by angrykoala** [comment]
Como? alumnos? ahora me he perdido :sweat:, desde el principio puse que era de 16:30 a 18:30 :sweat_smile:

**Comment by JJ** [comment]
Despiste mío entonces. Entendí en el telegram que era a las 18:30 Ya he
hecho la nueva reserva.

**Comment by angrykoala** [comment]
A lo mejor me equivoqué... unos creen que era hoy, otros a otra hora, que follón
Gracias!

**Comment by germaaan** [comment]
Pues ahora que comentais lo de la hora. Seguramente habría varias personas del máster que les resultaría interesante una charla introductoria de Node.js, sobretodo porque hay varias personas usándolo para su proyecto de la asignatura de Cloud Computing que no lo han usado nunca; pero hay un gran problema, justo a las 16:30 tenemos una asignatura "tocho" y la asistencia se controla mediante hoja de firmas.

**Comment by vrivas** [comment]
Pues... a ver en qué queda la cosa... yo estoy a expensas de lo que diga el
otro administrador de beejrs/granada y director de la OSL, así como del
propio profesor que impartirá la charla.
Gracias por avisar.

El 10 de noviembre de 2015, 23:58, German Martinez <notifications@github.com

> escribió:
> 
> Pues ahora que comentais lo de la hora. Seguramente habría varias personas
> del máster que les resultaría interesante una charla introductoria de
> Node.js, sobretodo porque hay varias personas usándolo para su proyecto de
> la asignatura de Cloud Computing que no lo han usado nunca; pero hay un
> gran problema, justo a las 16:30 tenemos una asignatura "tocho" y la
> asistencia se controla mediante hoja de firmas.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beerjs/granada/issues/3#issuecomment-155594841.

## 

_Victor Manuel Rivas Santos_

**Comment by angrykoala** [comment]
Sigo diciendo que siempre fue a las 16:30, si hay algún problema con esa hora es posible cambiarla (aunque habrá que avisar a todo el mundo)

**Comment by JJ** [comment]
Ya he reservado a las 16:30. NO problemo.

**Comment by germaaan** [comment]
Ok, pues a ver si nos podemos sumar. :thumbsup:

**Comment by vrivas** [comment]
En ese caso, todo solucionado. La información que aparece en portada es correcta. Por desgracia, a las 16:30 el que no podrá estar seré yo :/
