### ISSUE TITLE
Crear grupo de Telegram

### ISSUE THREAD

**Issue by germaaan** [beerjs/granada#6]
Así toda la gente interesada puede tener una forma de contacto rápida y directa.

**Comment by marco-fp** [comment]
JS-Beer geeks united

**Comment by vrivas** [comment]
Si lo veis oportuno adelante pero:
1) Lo habitual es que BeerJS se comunique por GitHub. Simplemente hay que marcar el correspondiente "Watch" y os llegará al correo.
2) Además, ya hay un grupo en Slack: https://beerjs.slack.com/messages/granada/  que además está sincronizado con GitHub por lo que, nuevamente, todo lo que pasa en el repo se comunica por ahí.  Si queréis uniros a este canal de slack, indicad el correo y os invito.

Cheers!

**Comment by JJ** [comment]
OK, pues slack entonces. Apúntame.

**Comment by vrivas** [comment]
Petición hecha.
Esperando a que conteste el adminsitrador del grupo en slack.

**Comment by vrivas** [comment]
Es más fácil de lo que pensaba. Solo tenéis acceder a este enlace: https://beerjs-slack-invite.herokuapp.com/ e insertar vuestra dirección de correo.
@JJ He introducido la tuya de gmail, así que supongo que te llegará un correo para que lo confirmes.
Saludos!

**Comment by germaaan** [comment]
Vale acabo de verlo y va perfecto, xD
